import 'server-only';
import type {Category,DeliveryZone,Media,Order,Product,ProductOptionGroup,SiteSettings} from '@/types';
import type {AppRole,DashboardSummary,CuisineType,HomepageSection,Restaurant,SellerApplication} from '@/types/marketplace';
import {siteConfig} from '@/config/site';import {createPublicClient as createClient} from '@/lib/supabase/public';import {isSupabaseConfigured} from '@/lib/supabase/env';
type Row=Record<string,unknown>;const bucket='restaurant-media';
function text(value:unknown,fallback=''){return typeof value==='string'?value:fallback}function number(value:unknown,fallback=0){return typeof value==='number'?value:fallback}function bool(value:unknown,fallback=false){return typeof value==='boolean'?value:fallback}
function publicUrl(path:unknown){if(!path||typeof path!=='string'||!isSupabaseConfigured())return undefined;const url=process.env.NEXT_PUBLIC_SUPABASE_URL?.replace(/\/rest\/v1\/?$/,'');return `${url}/storage/v1/object/public/${bucket}/${path}`}
function mapCategory(row:Row):Category{return{id:text(row.id),name:text(row.name),slug:text(row.slug),image:row.image_path?{id:`category-${text(row.id)}`,name:text(row.name),url:publicUrl(row.image_path)??'',alt:text(row.name),createdAt:text(row.created_at)}:undefined,visible:bool(row.is_active,true),order:number(row.sort_order)}}
function mapProduct(row:Row):Product{return{id:text(row.id),restaurantId:text(row.restaurant_id),sku:text(row.sku),name:text(row.name),slug:text(row.slug),categoryId:text(row.category_id),price:number(row.base_price),description:text(row.description),image:row.media&&typeof row.media==='object'?{id:text((row.media as Row).id),name:text(row.name),url:publicUrl((row.media as Row).path)??'',alt:text((row.media as Row).alt_text,text(row.name)),createdAt:text((row.media as Row).created_at)}:undefined,available:bool(row.availability),isFeatured:bool(row.is_featured),optionGroupIds:Array.isArray(row.product_option_group_links)?row.product_option_group_links.map(link=>text((link as Row).group_id)):[],archived:bool(row.is_archived),moderationStatus:text(row.moderation_status) as Product['moderationStatus'],hiddenByAdmin:bool(row.hidden_by_admin)}}
async function safe<T>(operation:()=>Promise<T>,fallback:()=>Promise<T>){if(!isSupabaseConfigured())return fallback();try{return await operation()}catch(error){if((error as {code?:string}).code!=='PGRST205')console.warn('Supabase indisponible, fallback local utilisé.',error);return fallback()}}

export function createMarketplaceRepositories(local:{products:()=>Promise<Product[]>;productBySlug:(slug:string)=>Promise<Product|undefined>;categories:()=>Promise<Category[]>;groups:()=>Promise<ProductOptionGroup[]>;orders:()=>Promise<Order[]>;orderByReference:(reference:string)=>Promise<Order|undefined>;media:()=>Promise<Media[]>;settings:()=>Promise<SiteSettings>;zones:()=>Promise<DeliveryZone[]>}){
 const categoryRepository={listPublic:()=>safe(async()=>{const db=await createClient();const{data,error}=await db.from('categories').select('*').eq('is_active',true).is('archived_at',null).order('sort_order');if(error)throw error;return(data as Row[]).map(mapCategory)},local.categories)};
 const productRepository={listPublic:()=>safe(async()=>{const db=await createClient();const{data,error}=await db.from('products').select('*,media(id,path,alt_text,created_at),product_option_group_links(group_id)').eq('is_archived',false).eq('hidden_by_admin',false).eq('moderation_status','approved').order('sort_order');if(error)throw error;return(data as Row[]).map(mapProduct)},local.products),listFeatured:async(limit=6)=>{const values=await productRepository.listPublic();const featured=values.filter(product=>product.isFeatured);return(featured.length?featured:values).slice(0,limit)},getBySlug:(slug:string)=>safe(async()=>{const db=await createClient();const{data,error}=await db.from('products').select('*,media(id,path,alt_text,created_at),product_option_group_links(group_id)').eq('slug',slug).eq('is_archived',false).maybeSingle();if(error)throw error;return data?mapProduct(data as Row):undefined},()=>local.productBySlug(slug)),create:async(input:{restaurantId:string;categoryId:string;name:string;description:string;basePrice:number;mediaId?:string;availability?:boolean})=>{const db=await createClient();const{data,error}=await db.from('products').insert({restaurant_id:input.restaurantId,category_id:input.categoryId,name:input.name,description:input.description,base_price:input.basePrice,media_id:input.mediaId,availability:input.availability??true,slug:'',sku:''}).select().single();if(error)throw error;return mapProduct(data as Row)}};
 const restaurantRepository={listPublic:async()=>{if(!isSupabaseConfigured())return[];const db=await createClient();const{data,error}=await db.from('restaurants').select('*').eq('validation_status','approved').order('name');if(error)throw error;return(data as Row[]).map(row=>({id:text(row.id),name:text(row.name),slug:text(row.slug),description:text(row.description),logoUrl:publicUrl(row.logo_path),coverUrl:publicUrl(row.cover_path),phone:text(row.phone),whatsapp:text(row.whatsapp),email:text(row.email),address:text(row.address),commune:text(row.commune),latitude:number(row.latitude),longitude:number(row.longitude),mapsUrl:text(row.maps_url),timezone:text(row.timezone,'Africa/Abidjan'),averagePrepMinutes:number(row.average_prep_minutes,25),deliveryAvailable:bool(row.delivery_available),pickupAvailable:bool(row.pickup_available),operatingStatus:text(row.operating_status) as Restaurant['operatingStatus'],validationStatus:text(row.validation_status) as Restaurant['validationStatus']}))},getBySlug:async(slug:string)=>{const rows=await restaurantRepository.listPublic();return rows.find(row=>row.slug===slug)},isOpen:async(id:string)=>{if(!isSupabaseConfigured())return false;const db=await createClient();const{data,error}=await db.rpc('restaurant_is_open',{target:id});if(error)throw error;return Boolean(data)}};
 const optionRepository={listForProduct:(productId:string)=>safe(async()=>{const db=await createClient();const{data,error}=await db.from('product_option_group_links').select('group:product_option_groups(*,options:product_options(*))').eq('product_id',productId).order('sort_order');if(error)throw error;return(data as Row[]).flatMap(link=>{const group=link.group as Row|undefined;if(!group)return[];return[{id:text(group.id),name:text(group.name),required:bool(group.is_required),multiple:number(group.max_choices,1)!==1,options:Array.isArray(group.options)?group.options.map(option=>({id:text((option as Row).id),name:text((option as Row).name),price:number((option as Row).price_delta),available:bool((option as Row).is_available,true)})):[]} satisfies ProductOptionGroup]})},local.groups)};
 const orderRepository={list:()=>safe(local.orders,local.orders),getByReference:(reference:string)=>safe(()=>local.orderByReference(reference),()=>local.orderByReference(reference)),vendorDashboard:async(restaurantId:string):Promise<DashboardSummary>=>{const db=await createClient();const start=new Date();start.setHours(0,0,0,0);const{data,error}=await db.from('restaurant_orders').select('subtotal,status').eq('restaurant_id',restaurantId).gte('created_at',start.toISOString());if(error)throw error;const rows=data as Row[];return{ordersToday:rows.length,revenueToday:rows.reduce((sum,row)=>sum+number(row.subtotal),0),pendingOrders:rows.filter(row=>['pending','confirmed','preparing'].includes(text(row.status))).length,unavailableProducts:0}}};
 const settingsRepository={get:()=>safe(async()=>{const db=await createClient();const{data,error}=await db.from('site_settings').select('key,value').eq('is_public',true);if(error)throw error;const values=Object.fromEntries((data as Row[]).map(row=>[text(row.key),row.value]));const contact=(values.contact??{}) as Row;return{restaurantName:text((values.brand as Row)?.name,siteConfig.brand.name),phone:text(contact.phone,siteConfig.contact.phone),email:text(contact.email,siteConfig.contact.email),address:text(contact.address,siteConfig.contact.address),currency:'XOF',deliveryEnabled:true,pickupEnabled:true}},local.settings),getRaw:async()=>{if(!isSupabaseConfigured())return{};const db=await createClient();const{data,error}=await db.from('site_settings').select('key,value').eq('is_public',true);if(error)throw error;return Object.fromEntries((data as Row[]).map(row=>[text(row.key),row.value]))},getHomepageSections:async():Promise<HomepageSection[]>=>{if(!isSupabaseConfigured())return[];const db=await createClient();const{data,error}=await db.from('homepage_sections').select('*,media(path)').eq('is_visible',true).order('sort_order');if(error)throw error;return(data as Row[]).map(row=>({id:text(row.id),sectionKey:text(row.section_key),title:text(row.title),subtitle:text(row.subtitle),body:text(row.body),imageUrl:row.media&&typeof row.media==='object'?publicUrl((row.media as Row).path):undefined,productId:text(row.product_id)||undefined,sortOrder:number(row.sort_order),isVisible:bool(row.is_visible)}))}};
 const mediaRepository={list:()=>safe(async()=>{const db=await createClient();const{data,error}=await db.from('media').select('*').order('created_at',{ascending:false});if(error)throw error;return(data as Row[]).map(row=>({id:text(row.id),name:text(row.file_name),url:publicUrl(row.path)??'',alt:text(row.alt_text),createdAt:text(row.created_at)}))},local.media)};
 const cuisineTypeRepository={list:async():Promise<CuisineType[]>=>{if(!isSupabaseConfigured())return[];const db=await createClient();const{data,error}=await db.from('cuisine_types').select('*').eq('is_active',true).order('sort_order');if(error)throw error;return(data as Row[]).map(row=>({id:text(row.id),name:text(row.name),slug:text(row.slug),isActive:bool(row.is_active),sortOrder:number(row.sort_order)}))}};
 const sellerApplicationRepository={create:async(input:Omit<SellerApplication,'id'|'status'|'adminNotes'>)=>{const db=await createClient();const{data,error}=await db.from('seller_applications').insert({user_id:input.userId,restaurant_name:input.restaurantName,description:input.description,phone:input.phone,address:input.address,commune:input.commune,status:'draft'}).select().single();if(error)throw error;return data}};
 const promotionRepository={listPublic:async()=>{if(!isSupabaseConfigured())return[];const db=await createClient();const{data,error}=await db.from('promotions').select('*').eq('is_active',true);if(error)throw error;return data}};
 const userRepository={setRole:async(userId:string,role:AppRole)=>{const db=await createClient();const{data,error}=await db.rpc('admin_set_user_role',{target_user:userId,new_role:role});if(error)throw error;return data}};
 return{categoryRepository,productRepository,restaurantRepository,optionRepository,orderRepository,settingsRepository,mediaRepository,cuisineTypeRepository,sellerApplicationRepository,promotionRepository,userRepository};
}
