import Link from 'next/link';
import {notFound} from 'next/navigation';
import {AdminHeader} from '@/components/admin-ui';
import {updateAdminOrderStatus} from '@/app/admin/actions';
import {requireAdmin} from '@/lib/auth/admin';
import {formatPrice} from '@/lib/utils';
import {getAdminOrder,orderLabels} from '@/services/admin-marketplace';
type Item={id:string;product_name:string;quantity:number;options:unknown;line_total:number};
type Event={created_at:string;to_status:string;actor?:{display_name?:string}|{display_name?:string}[]};
type SubOrder={id:string;status:string;subtotal:number;delivery_fee:number;restaurant:{name?:string}|{name?:string}[];items:Item[];events?:Event[]};
export default async function Page({params}:{params:Promise<{id:string}>}){
 await requireAdmin();const{id}=await params;const order=await getAdminOrder(id);if(!order)notFound();
 return <><AdminHeader eyebrow="Commande globale" title={order.reference} action={<Link className="btn btn-outline" href="/admin/orders">← Commandes</Link>}/><div className="admin-detail-grid"><section className="admin-card"><h2>Client</h2><dl className="detail-list"><div><dt>Nom</dt><dd>{order.customer_name}</dd></div><div><dt>Téléphone</dt><dd>{order.customer_phone}</dd></div><div><dt>Mode</dt><dd>{order.fulfillment==='delivery'?'Livraison':'Retrait'}</dd></div>{order.address?<div><dt>Adresse</dt><dd>{order.address}</dd></div>:null}<div><dt>Paiement</dt><dd>{order.payment_status==='paid'?'Payé':'En attente'}</dd></div>{order.customer_note?<div><dt>Note</dt><dd>{order.customer_note}</dd></div>:null}</dl></section><aside className="admin-card"><h2>Total</h2><strong className="admin-total">{formatPrice(order.total)}</strong><p className="muted">Créée le {new Intl.DateTimeFormat('fr-FR',{dateStyle:'long',timeStyle:'short'}).format(new Date(order.created_at))}</p></aside></div>{(order.restaurant_orders as SubOrder[]).map(sub=>{const restaurant=Array.isArray(sub.restaurant)?sub.restaurant[0]:sub.restaurant;return <section className="admin-card admin-suborder" key={sub.id}><div className="card-head"><div><h2>{restaurant?.name}</h2><span className="vendor-badge">{orderLabels[sub.status]}</span></div><strong>{formatPrice(sub.subtotal+sub.delivery_fee)}</strong></div>{sub.items.map(item=><div className="order-line" key={item.id}><span><b>{item.quantity} × {item.product_name}</b><small>{Array.isArray(item.options)&&item.options.length?(item.options as {name?:string}[]).map(option=>option.name).filter(Boolean).join(', '):'Sans option'}</small></span><strong>{formatPrice(item.line_total)}</strong></div>)}<form action={updateAdminOrderStatus} className="admin-inline-form"><input type="hidden" name="order_id" value={id}/><input type="hidden" name="restaurant_order_id" value={sub.id}/><select name="status" defaultValue={sub.status}>{Object.entries(orderLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><button className="btn btn-dark">Mettre à jour</button></form>{sub.events?.length?<details><summary>Historique des statuts</summary>{sub.events.map((event,index)=>{const actor=Array.isArray(event.actor)?event.actor[0]:event.actor;return <p className="muted" key={`${event.created_at}-${index}`}>{new Intl.DateTimeFormat('fr-FR',{dateStyle:'short',timeStyle:'short'}).format(new Date(event.created_at))} · {orderLabels[event.to_status]}{actor?.display_name?` · ${actor.display_name}`:''}</p>})}</details>:null}</section>})}</>
}
