import 'server-only';
import {formatPrice} from '@/lib/utils';
export type OrderEmailItem={productName:string;quantity:number;options:string[];lineTotal:number};
export type OrderEmailInput={name?:string;customerPhone?:string;createdAt?:string;reference:string;orderId?:string;restaurantOrderId?:string;restaurantName?:string;restaurants?:string[];items?:OrderEmailItem[];total?:number;fulfillment?:'delivery'|'pickup';zone?:string;address?:string;instructions?:string;paymentStatus?:string;trackingToken?:string};
export type EmailTemplate={subject:string;html:string;text:string};
const esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]??char));
const siteUrl=()=>String(process.env.NEXT_PUBLIC_SITE_URL||process.env.SITE_URL||'https://comeandeat.org').replace(/\/$/,'');
const line=(label:string,value:unknown)=>value?`<p style="margin:6px 0"><strong>${esc(label)} :</strong> ${esc(value)}</p>`:'';
const button=(label:string,url:string)=>`<p style="margin:28px 0"><a href="${esc(url)}" style="background:#0b513c;color:#fff;text-decoration:none;padding:13px 20px;border-radius:999px;display:inline-block;font-weight:700">${esc(label)}</a></p>`;
const itemBlock=(rows:OrderEmailItem[]=[])=>(rows.length?`<div style="border-top:1px solid #e6e2da;margin-top:20px;padding-top:12px">${rows.map(item=>`<p style="margin:10px 0"><strong>${item.quantity} × ${esc(item.productName)}</strong>${item.options.length?`<br><span style="color:#59645f">${item.options.map(esc).join(' · ')}</span>`:''}<br>${formatPrice(item.lineTotal)}</p>`).join('')}</div>`:'');
function layout(preview:string,title:string,body:string,cta=''){const logo=`${siteUrl()}/brand/come-eat-logo-transparent.webp`;return{html:`<!doctype html><html lang="fr"><head><meta name="viewport" content="width=device-width"><meta charset="utf-8"><title>${esc(preview)}</title></head><body style="margin:0;background:#f6f3ec;color:#10251f;font-family:Arial,sans-serif"><div style="display:none;max-height:0;overflow:hidden">${esc(preview)}</div><main style="max-width:600px;margin:auto;padding:24px 14px"><section style="background:#fff;border:1px solid #e9e4da;border-radius:22px;padding:28px"><img src="${logo}" width="132" alt="Come & Eat" style="display:block;height:auto;max-width:132px"><h1 style="font-size:28px;line-height:1.15;margin:26px 0 16px">${esc(title)}</h1><div style="font-size:16px;line-height:1.6">${body}${cta}</div></section><p style="text-align:center;color:#68736f;font-size:12px;line-height:1.5">Come & Eat · Le goût qui parle<br>Besoin d’aide ? Répondez simplement à cet email.</p></main></body></html>`,text:`${title}\n\n${body.replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}${cta?'\n\nConsultez Come & Eat : '+siteUrl():''}`}}
const tracking=(input:OrderEmailInput)=>`${siteUrl()}/order/${encodeURIComponent(input.reference)}?token=${encodeURIComponent(input.trackingToken||'')}`;
const orderBody=(input:OrderEmailInput)=>`${line('Référence',input.reference)}${line('Date',input.createdAt?new Intl.DateTimeFormat('fr-FR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(input.createdAt)):'')}${line('Client',input.name)}${line('Téléphone',input.customerPhone)}${input.restaurantName?line('Restaurant',input.restaurantName):''}${input.restaurants?.length?line('Restaurants',input.restaurants.join(', ')):''}${line('Mode',input.fulfillment==='pickup'?'Retrait':'Livraison')}${line('Zone',input.zone)}${line('Adresse',input.address)}${line('Instructions',input.instructions)}${itemBlock(input.items)}${typeof input.total==='number'?`<p style="font-size:20px"><strong>Total : ${formatPrice(input.total)}</strong></p>`:''}`;
export function welcomeTemplate(name?:string):EmailTemplate{const c=layout('Bienvenue sur Come & Eat','Bienvenue sur Come & Eat',`<p>Bonjour ${esc(name||'')},</p><p>Votre espace est prêt. Découvrez les restaurants et commandez simplement.</p>`,button('Découvrir les restaurants',`${siteUrl()}/restaurants`));return{subject:'Bienvenue sur Come & Eat',...c}}
export function passwordChangedTemplate(name?:string):EmailTemplate{const c=layout('Votre mot de passe a été modifié','Mot de passe modifié',`<p>Bonjour ${esc(name||'')},</p><p>Le mot de passe de votre compte Come & Eat vient d’être modifié.</p><p>Si vous n’êtes pas à l’origine de ce changement, contactez immédiatement le support.</p>`);return{subject:'Votre mot de passe Come & Eat a été modifié',...c}}
export function orderReceivedTemplate(input:OrderEmailInput):EmailTemplate{const c=layout('Nous avons reçu votre commande','Commande bien reçue',`<p>Bonjour ${esc(input.name||'')},</p>${orderBody(input)}<p><strong>Paiement à vérifier.</strong> Votre commande sera transmise au restaurant après confirmation du paiement.</p>`,button('Suivre ma commande',tracking(input)));return{subject:'Nous avons reçu votre commande',...c}}
export function adminOrderTemplate(input:OrderEmailInput):EmailTemplate{const c=layout('Nouvelle commande à vérifier','Nouvelle commande Come & Eat à vérifier',orderBody(input),button('Voir la commande',`${siteUrl()}/admin/orders/${input.orderId}`));return{subject:'Nouvelle commande Come & Eat à vérifier',...c}}
export function paymentConfirmedTemplate(input:OrderEmailInput):EmailTemplate{const c=layout('Votre paiement est confirmé','Paiement confirmé',`<p>Votre paiement pour la commande <strong>${esc(input.reference)}</strong> est confirmé.</p>${typeof input.total==='number'?`<p>Montant payé : <strong>${formatPrice(input.total)}</strong></p>`:''}<p>Votre commande a été transmise au restaurant.</p>`,button('Suivre ma commande',tracking(input)));return{subject:'Votre paiement est confirmé',...c}}
export function vendorNewOrderTemplate(input:OrderEmailInput):EmailTemplate{const c=layout('Nouvelle commande Come & Eat','Nouvelle commande à traiter',orderBody(input),button('Voir la commande',`${siteUrl()}/vendor/orders/${input.restaurantOrderId}`));return{subject:'Nouvelle commande Come & Eat',...c}}
const lifecycle:Record<string,{subject:string;title:(restaurant?:string)=>string;body:string}>={confirmed:{subject:'Votre commande a été confirmée',title:r=>`${r||'Le restaurant'} a confirmé votre commande`,body:'La préparation va pouvoir commencer.'},preparing:{subject:'Votre commande est en préparation',title:r=>`${r||'Le restaurant'} prépare votre commande`,body:'Votre commande est en cours de préparation.'},ready:{subject:'Votre commande est prête',title:r=>`${r||'Le restaurant'} a terminé la préparation`,body:'Votre commande sera bientôt prise en charge pour la livraison.'},ready_for_pickup:{subject:'Votre commande est prête à être récupérée',title:()=>`Votre commande est prête pour le retrait`,body:'Vous pouvez venir la récupérer au restaurant.'},out_for_delivery:{subject:'Votre commande est en route',title:()=>`Votre commande est en cours de livraison`,body:'Elle est en route vers votre adresse.'},delivered:{subject:'Votre commande a été livrée',title:()=>`Commande livrée`,body:'Merci d’avoir commandé avec Come & Eat.'},collected:{subject:'Votre commande a été récupérée',title:()=>`Commande remise au client`,body:'Merci d’avoir commandé avec Come & Eat.'},cancelled:{subject:'Une partie de votre commande a été annulée',title:r=>`Commande annulée chez ${r||'le restaurant'}`,body:'Si un paiement a été effectué, son traitement sera vérifié séparément. Cet email ne confirme pas un remboursement.'}};
export function lifecycleTemplate(status:string,input:OrderEmailInput):EmailTemplate{const entry=lifecycle[status]??lifecycle.confirmed;const c=layout(entry.subject,entry.title(input.restaurantName),`${orderBody(input)}<p>${entry.body}</p>`,button('Suivre ma commande',tracking(input)));return{subject:entry.subject,...c}}
