import Image from 'next/image';
import {AdminHeader} from '@/components/admin-ui';
import {requireAdmin} from '@/lib/auth/admin';
import {getAdminCategories,getAdminProducts,getAdminRestaurants,moderationLabels} from '@/services/admin-marketplace';
import {moderateProduct} from '@/app/admin/actions';
import {formatPrice} from '@/lib/utils';

export default async function Page({searchParams}:{searchParams:Promise<{q?:string;restaurant?:string;category?:string;state?:string}>}){
  await requireAdmin(); const filters=await searchParams;
  const [products,restaurants,categories]=await Promise.all([getAdminProducts({search:filters.q,restaurant:filters.restaurant,category:filters.category,state:filters.state}),getAdminRestaurants(),getAdminCategories()]);
  return <><AdminHeader eyebrow="Catalogue global" title="Produits"/><form className="admin-filters"><input name="q" defaultValue={filters.q} placeholder="Rechercher un produit"/><select name="restaurant" defaultValue={filters.restaurant}><option value="">Tous les restaurants</option>{restaurants.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><select name="category" defaultValue={filters.category}><option value="">Toutes les catégories</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select name="state" defaultValue={filters.state}><option value="">Tous les états</option><option value="available">Disponibles</option><option value="unavailable">Indisponibles</option><option value="pending">À vérifier</option><option value="hidden">Masqués</option><option value="archived">Archivés</option></select><button className="btn btn-dark">Filtrer</button></form><section className="admin-card">{products.length?<div className="table-wrap"><table><thead><tr><th>Produit</th><th>Restaurant</th><th>Catégorie</th><th>Prix</th><th>État</th><th>Actions</th></tr></thead><tbody>{products.map(product=>{const restaurant=Array.isArray(product.restaurant)?product.restaurant[0]:product.restaurant;const category=Array.isArray(product.category)?product.category[0]:product.category;return <tr key={product.id}><td><div className="product-cell">{product.imageUrl?<span className="mini-photo"><Image src={product.imageUrl} alt="" fill sizes="48px"/></span>:null}<span><strong>{product.name}</strong>{product.moderation_note?<small>{product.moderation_note}</small>:null}</span></div></td><td>{restaurant?.name??'—'}</td><td>{category?.name??'Sans catégorie'}</td><td><strong>{formatPrice(product.base_price)}</strong></td><td><span className={`vendor-badge ${product.hidden_by_admin?'danger':product.availability?'success':''}`}>{product.is_archived?'Archivé':product.hidden_by_admin?'Masqué par Come & Eat':moderationLabels[product.moderation_status]}</span></td><td><div className="table-actions"><form action={moderateProduct}><input type="hidden" name="id" value={product.id}/><button name="action" value={product.availability?'unavailable':'available'}>{product.availability?'Rendre indisponible':'Rendre disponible'}</button></form><details><summary>Modérer</summary><form action={moderateProduct} className="compact-form"><input type="hidden" name="id" value={product.id}/><textarea name="note" placeholder="Note visible par le vendeur"/><button name="action" value={product.hidden_by_admin?'show':'hide'}>{product.hidden_by_admin?'Réafficher':'Masquer'}</button><button name="action" value="flag">Demander une correction</button><button className="danger-link" name="action" value="archive">Archiver</button></form></details></div></td></tr>})}</tbody></table></div>:<div className="admin-empty"><strong>Aucun produit</strong><p>Aucun produit ne correspond à ces filtres.</p></div>}</section></>
}
