import Image from 'next/image';
import Link from 'next/link';
import { ProductCard } from '@/components/product-card';
import { localCatalogRepository } from '@/services/repositories';

export default async function Home(){
 const [allProducts,categories]=await Promise.all([localCatalogRepository.getProducts(),localCatalogRepository.getCategories()]);
 const products=allProducts.filter(p=>p.available).slice(0,4);
 return <>
  <section className="hero"><div className="store-container"><div className="hero-grid"><div className="hero-copy"><p className="hero-badge">✣ Gastronomie ivoirienne & livraison express</p><h1>COME & EAT<br/><span>LE GOÛT QUI </span><em>PARLE</em></h1><p>Savourez une cuisine généreuse préparée minute avec des ingrédients frais. Des portions gourmandes, livrées chaudes partout à Abidjan.</p><div className="hero-actions"><Link href="/menu" className="btn btn-orange">▣ Commander maintenant <span>→</span></Link><Link href="/menu" className="btn btn-ghost">⚔ Découvrir la carte</Link></div><div className="hero-proof"><span>◷ Livré en 25 min</span><span>♧ 100% frais</span><span>♢ Paiement Wave/MoMo</span></div></div><div className="hero-visual"><div className="hero-card"><span className="daily-badge">🔥 Plat star du jour</span><Image src="/images/burger.svg" alt="Plat signature Come & Eat" fill priority sizes="(max-width: 800px) 100vw, 45vw"/><div><strong>Formule Burger Signature</strong><span>7 000 FCFA</span></div><Link href="/menu/formule-burger">Personnaliser & commander →</Link></div></div></div></div></section>
  <section className="concept section"><div className="store-container"><div className="center-heading"><span className="soft-pill">♧ Le concept Come & Eat</span><h2>Manger généreusement,<br/>sans compromis</h2><p>Des recettes simples, une préparation minute et le plaisir de partager.</p></div><div className="benefits four"><div className="benefit tone-green"><span>♧</span><small>100% Frais</small><h3>Naturel</h3><p>Des ingrédients locaux sélectionnés chaque matin.</p><b>Traçabilité garantie</b></div><div className="benefit tone-coral"><span>♡</span><small>Fait maison</small><h3>Authentique</h3><p>Des recettes vraies, généreuses et pleines de caractère.</p><b>Recettes du terroir</b></div><div className="benefit tone-gold"><span>♙</span><small>À partager</small><h3>Convivial</h3><p>Le plaisir de bien manger ensemble à tout moment.</p><b>Moments chaleureux</b></div><div className="benefit tone-blue"><span>♙</span><small>Qualité</small><h3>Certifié</h3><p>Une attention constante au goût et à l’hygiène.</p><b>Exigence maison</b></div></div></div></section>
  <section className="section popular-section"><div className="store-container"><div className="section-head"><div><p className="section-kicker">🔥 Les incontournables</p><h2>Nos plats phares & best-sellers</h2></div><Link href="/menu" className="btn btn-outline">Voir toute la carte ({allProducts.length} plats) →</Link></div><div className="product-grid home-products">{products.map(p=><ProductCard key={p.id} product={p} featured/>)}</div></div></section>
  <section className="section category-section"><div className="store-container"><div className="section-head"><div><p className="section-kicker">🍽 Pour toutes les envies</p><h2>Explorez notre carte</h2></div></div><div className="category-grid">{categories.filter(c=>c.visible).map((c,i)=><Link href={`/menu?category=${c.slug}`} key={c.id}><span>{['🍔','🍟','🥤','🍰'][i]}</span><div><strong>{c.name}</strong><small>Découvrir →</small></div></Link>)}</div></div></section>
  <section className="cta-section"><div className="store-container"><div><h2>Envie d’un repas savoureux<br/>et chaud maintenant ?</h2><p>Passez commande en 3 clics. Choisissez, personnalisez et régalez-vous !</p><div><Link className="btn btn-orange" href="/menu">▣ Consulter le menu & commander</Link><Link className="btn btn-ghost" href="/contact">☎ Service client & horaires</Link></div></div></div></section>
 </>
}