'use client';
import Link from 'next/link';
import {FormEvent,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {useCart} from './cart-provider';
import {formatPrice} from '@/lib/utils';
import type {DeliveryZone} from '@/types';
import {placeOrder,quoteOrder,type CheckoutQuote} from '@/app/(public)/checkout/actions';

export function CheckoutForm({zones}:{zones:DeliveryZone[]}){
 const cart=useCart(),router=useRouter(),key=useRef(crypto.randomUUID());
 const[fulfillment,setFulfillment]=useState<'delivery'|'pickup'>(zones.length?'delivery':'pickup'),[zone,setZone]=useState(zones[0]?.id??'');
 const[loading,setLoading]=useState(false),[quoting,setQuoting]=useState(false),[error,setError]=useState(''),[promo,setPromo]=useState(''),[quote,setQuote]=useState<CheckoutQuote|null>(null);
 const items=cart.items.map(item=>({productId:item.productId,quantity:item.quantity,optionIds:item.selections.map(s=>s.optionId)}));
 const restaurantCount=Math.max(1,new Set(cart.items.map(i=>i.restaurantId).filter(Boolean)).size),fee=fulfillment==='delivery'?(zones.find(z=>z.id===zone)?.fee??0)*restaurantCount:0;
 const applyPromo=async()=>{setQuoting(true);setError('');const result=await quoteOrder({fulfillment,deliveryZoneId:fulfillment==='delivery'?zone:undefined,promotionCode:promo,items});if(result.ok)setQuote(result.quote);else{setQuote(null);setError(result.error)}setQuoting(false)};
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!cart.items.length||loading)return;if(fulfillment==='delivery'&&!zones.length){setError('Les livraisons sont fermées pour le moment. Vous pouvez choisir le retrait.');return}setLoading(true);setError('');const form=new FormData(e.currentTarget);const result=await placeOrder({customerName:String(form.get('name')??''),customerPhone:String(form.get('phone')??''),customerEmail:String(form.get('email')??''),fulfillment,address:String(form.get('address')??''),commune:String(form.get('commune')??''),note:String(form.get('instructions')??''),wantsCutlery:form.get('cutlery')==='on',deliveryZoneId:fulfillment==='delivery'?zone:undefined,promotionCode:promo,idempotencyKey:key.current,items});if(!result.ok){setError(result.error);setLoading(false);return}sessionStorage.setItem(`come-eat-order-${result.order.reference}`,JSON.stringify({paymentUrl:result.payment.url,merchantPhone:result.payment.merchantPhone}));cart.clear();router.push(`/order/${result.order.reference}?token=${result.order.tracking_token}`)};
 if(!cart.items.length)return <div className="store-container"><div className="empty-state"><h2>Votre panier est vide</h2><Link className="btn btn-orange" href="/menu">Retour au menu</Link></div></div>;
 const subtotal=quote?.subtotal??cart.subtotal,delivery=quote?.delivery_fee??fee,discount=quote?.discount_total??0,total=quote?.total??subtotal+delivery;
 return <form onSubmit={submit} className="store-container checkout-grid"><div className="checkout-flow">
 <section className="checkout-card"><div className="step-title"><span>1</span><div><small>Vos coordonnées</small><h2>Comment vous joindre ?</h2></div></div><div className="form-grid"><div className="field"><label htmlFor="name">Nom complet</label><input name="name" id="name" required autoComplete="name"/></div><div className="field"><label htmlFor="phone">Téléphone</label><input name="phone" id="phone" required type="tel" autoComplete="tel" placeholder="+225 07…"/></div><div className="field full"><label htmlFor="email">Email <small>(facultatif)</small></label><input name="email" id="email" type="email" autoComplete="email"/></div></div></section>
 <section className="checkout-card"><div className="step-title"><span>2</span><div><small>Mode de réception</small><h2>Livraison ou retrait ?</h2></div></div>{!zones.length?<div className="notice" role="status"><strong>Les livraisons sont fermées pour le moment.</strong><br/>Vous pouvez toujours choisir le retrait.</div>:null}<div className="choice-grid">{zones.length?<label className={fulfillment==='delivery'?'choice-card selected':'choice-card'}><input type="radio" checked={fulfillment==='delivery'} onChange={()=>{setFulfillment('delivery');setQuote(null)}}/><b>Livraison</b><small>À l’adresse indiquée</small></label>:null}<label className={fulfillment==='pickup'?'choice-card selected':'choice-card'}><input type="radio" checked={fulfillment==='pickup'} onChange={()=>{setFulfillment('pickup');setQuote(null)}}/><b>Retrait</b><small>Directement au restaurant</small></label></div>{fulfillment==='delivery'?<div className="form-grid delivery-fields"><div className="field full"><label htmlFor="address">Adresse et repère</label><input name="address" id="address" required/></div><div className="field"><label htmlFor="commune">Commune</label><input name="commune" id="commune" required/></div><div className="field"><label htmlFor="zone">Zone de livraison</label><select id="zone" value={zone} onChange={e=>{setZone(e.target.value);setQuote(null)}}>{zones.map(z=><option key={z.id} value={z.id}>{z.name} — {formatPrice(z.fee)}</option>)}</select></div></div>:null}<div className="field"><label htmlFor="instructions">Instructions pour la commande <small>(facultatif)</small></label><textarea name="instructions" id="instructions" rows={3}/></div><label className="cutlery"><input name="cutlery" type="checkbox"/><span>Ajouter des couverts</span></label></section>
 <section className="checkout-card"><div className="step-title"><span>3</span><div><small>Paiement</small><h2>Payer avec Wave</h2></div></div><div className="payment-grid"><label className="selected"><input type="radio" defaultChecked/><b>Wave</b><small>Le paiement sera vérifié par Come & Eat.</small></label></div></section></div>
 <aside className="order-summary checkout-summary"><span className="summary-eyebrow">Votre commande</span><h2>Récapitulatif</h2>{cart.items.map(i=><div className="checkout-line" key={i.id}><span><b>{i.quantity} × {i.name}</b><small>{i.selections.map(s=>s.name).join(', ')}</small></span><strong>{formatPrice((i.unitPrice+i.selections.reduce((s,o)=>s+o.price,0))*i.quantity)}</strong></div>)}<div className="field promo-field"><label htmlFor="promo">Code promo</label><div className="promo-control"><input id="promo" value={promo} onChange={e=>{setPromo(e.target.value);setQuote(null)}} placeholder="Votre code"/><button type="button" className="btn btn-outline" disabled={quoting||!promo.trim()} onClick={applyPromo}>{quoting?'Vérification…':'Appliquer'}</button></div>{discount>0?<small className="form-feedback success" role="status">Code appliqué{quote?.promotion_name?` : ${quote.promotion_name}`:''}</small>:null}</div><div className="summary-row"><span>Sous-total</span><strong>{formatPrice(subtotal)}</strong></div>{discount>0?<div className="summary-row discount"><span>Réduction</span><strong>-{formatPrice(discount)}</strong></div>:null}<div className="summary-row"><span>Livraison</span><strong>{formatPrice(delivery)}</strong></div><div className="summary-row total"><strong>Total</strong><strong>{formatPrice(total)}</strong></div><p className="muted">Le serveur vérifie le montant final.</p>{error?<p className="form-error" role="alert">{error}</p>:null}<button className="btn btn-orange summary-cta" disabled={loading}>{loading?'Vérification en cours…':'Créer et payer ma commande'}</button></aside></form>;
}
