'use client';

import { ActionForm, VendorMediaPicker, type MediaChoice } from '@/components/vendor-forms';
import { updateOfficialStore } from '@/app/admin/store/actions';

export function OfficialStoreForm({ store, cuisineIds, cuisines, media }: { store: Record<string, unknown>; cuisineIds: string[]; cuisines: Array<{ id: string; name: string }>; media: MediaChoice[] }) {
  const id = String(store.id);
  return <ActionForm action={updateOfficialStore} submitLabel="Enregistrer la boutique">
    <section className="vendor-card"><h2>Identité et photos</h2><div className="vendor-photo-grid"><div><strong>Logo</strong><VendorMediaPicker restaurantId={id} type="logo" pathName="logo_path" initialPath={String(store.logo_path ?? '')} items={media} /></div><div><strong>Couverture</strong><VendorMediaPicker restaurantId={id} type="cover" pathName="cover_path" initialPath={String(store.cover_path ?? '')} items={media} /></div></div><div className="vendor-form-grid"><label className="field full"><span>Nom</span><input name="name" defaultValue={String(store.name ?? '')} required /></label><label className="field full"><span>Description</span><textarea name="description" rows={4} defaultValue={String(store.description ?? '')} /></label></div></section>
    <section className="vendor-card"><h2>Contact et adresse</h2><div className="vendor-form-grid"><label className="field"><span>Téléphone</span><input name="phone" type="tel" defaultValue={String(store.phone ?? '')} /></label><label className="field"><span>WhatsApp</span><input name="whatsapp" type="tel" defaultValue={String(store.whatsapp ?? '')} /></label><label className="field full"><span>Email</span><input name="email" type="email" defaultValue={String(store.email ?? '')} /></label><label className="field full"><span>Adresse</span><input name="address" defaultValue={String(store.address ?? '')} /></label><label className="field"><span>Commune / zone</span><input name="commune" defaultValue={String(store.commune ?? '')} /></label><label className="field"><span>Lien Maps <small>facultatif</small></span><input name="maps_url" type="url" defaultValue={String(store.maps_url ?? '')} /></label><label className="field"><span>Latitude <small>facultatif</small></span><input name="latitude" type="number" step="any" defaultValue={String(store.latitude ?? '')} /></label><label className="field"><span>Longitude <small>facultatif</small></span><input name="longitude" type="number" step="any" defaultValue={String(store.longitude ?? '')} /></label></div></section>
    <section className="vendor-card"><h2>Service</h2><label className="field prep-time"><span>Délai moyen de préparation</span><span><input name="average_prep_minutes" type="number" min="0" max="360" defaultValue={Number(store.average_prep_minutes ?? 25)} /><b>minutes</b></span></label><fieldset className="cuisine-choices"><legend>Types de cuisine</legend>{cuisines.map((cuisine) => <label key={cuisine.id}><input type="checkbox" name="cuisine_ids" value={cuisine.id} defaultChecked={cuisineIds.includes(cuisine.id)} /><span>{cuisine.name}</span></label>)}</fieldset><div className="option-checks"><label><input type="checkbox" name="delivery_available" defaultChecked={Boolean(store.delivery_available)} /><span>Livraison</span></label><label><input type="checkbox" name="pickup_available" defaultChecked={Boolean(store.pickup_available)} /><span>Retrait</span></label></div></section>
  </ActionForm>;
}
