'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import {formatPrice} from '@/lib/utils';
type Item={product_name:string;quantity:number;options:Array<{name?:string}>;line_total:number};
type Event={from_status?:string;to_status:string;created_at:string};
type Sub={id:string;status:string;subtotal:number;delivery_fee:number;restaurant:{name:string};items:Item[];events:Event[]};
type Status={reference:string;total:number;subtotal:number;delivery_fee:number;discount_total:number;payment_status:string;fulfillment:'delivery'|'pickup';address?:string;commune?:string;customer_note?:string;created_at:string;restaurant_orders:Sub[]};
type Payment={paymentUrl:string;merchantPhone:string};
const labels:Record<string,string>={pending:'Nouvelle',confirmed:'Confirmée',preparing:'En préparation',ready:'Prête',ready_for_pickup:'Prête pour retrait',out_for_delivery:'En livraison',delivered:'Livrée',collected:'Remise au client',cancelled:'Annulée'};
const messages:Record<string,string>={pending:'Votre commande a bien été reçue.',confirmed:'Votre commande a été confirmée.',preparing:'Le restaurant prépare votre commande.',ready:'Votre commande est prête.',ready_for_pickup:'Votre commande est prête à être récupérée.',out_for_delivery:'Votre commande est en cours de livraison.',delivered:'Commande livrée.',collected:'Commande remise au client.',cancelled:'Cette commande a été annulée.'};
const deliverySteps=['pending','confirmed','preparing','ready','out_for_delivery','delivered'],pickupSteps=['pending','confirmed','preparing','ready_for_pickup','collected'];
export function OrderStatus({reference,token}:{reference:string;token?:string}){
 const[order,setOrder]=useState<Status|null>(null),[missing,setMissing]=useState(false),[payment,setPayment]=useState<Payment|null>(null),[refreshing,setRefreshing]=useState(false);
 const refresh=useCallback(async(silent=false)=>{if(!token)return;if(!silent)setRefreshing(true);try{const response=await fetch(`/api/orders/${encodeURIComponent(reference)}?token=${encodeURIComponent(token)}`,{cache:'no-store'});if(!response.ok)throw new Error();setOrder(await response.json());setMissing(false)}catch{setMissing(true)}finally{setRefreshing(false)}},[reference,token]);
 useEffect(()=>{const savedTimer=window.setTimeout(()=>{const saved=sessionStorage.getItem(`come-eat-order-${reference}`);if(saved)try{setPayment(JSON.parse(saved))}catch{}},0);const initialTimer=window.setTimeout(()=>void refresh(true),0);const timer=window.setInterval(()=>{if(document.visibilityState==='visible')void refresh(true)},15000);return()=>{window.clearTimeout(savedTimer);window.clearTimeout(initialTimer);window.clearInterval(timer)}},[reference,refresh]);
 if(!token||missing)return <div className="container"><div className="card empty"><h2>Commande introuvable</h2><p>Utilisez le lien privé obtenu lors de la commande.</p><Link className="btn btn-dark" href="/menu">Retour au menu</Link></div></div>;
 if(!order)return <div className="container"><div className="card empty"><p>Chargement du suivi…</p></div></div>;
 return <div className="container order-tracking"><section className="tracking-head"><div><p className="eyebrow">Commande {reference}</p><h1 className="page-title">{messages[order.restaurant_orders[0]?.status??'pending']}</h1><p>Créée le {new Intl.DateTimeFormat('fr-FR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(order.created_at))}</p></div><button type="button" className="btn btn-outline" disabled={refreshing} onClick={()=>void refresh()}>{refreshing?'Actualisation…':'Actualiser'}</button></section>
 <div className="tracking-summary"><span>Statut du paiement <strong>{order.payment_status==='paid'?'Payé':'Paiement à vérifier'}</strong></span><span>Mode <strong>{order.fulfillment==='delivery'?'Livraison':'Retrait'}</strong></span><span>Total <strong>{formatPrice(order.total)}</strong></span></div>
 {payment&&order.payment_status!=='paid'?<div className="payment-next"><a className="btn btn-orange" href={payment.paymentUrl} target="_blank" rel="noopener noreferrer">Payer avec Wave</a><p>Compte marchand : <strong>{payment.merchantPhone}</strong><br/>Référence : <strong>{reference}</strong>.</p></div>:null}
 {order.restaurant_orders.map(sub=>{const steps=order.fulfillment==='delivery'?deliverySteps:pickupSteps;const current=Math.max(0,steps.indexOf(sub.status));return <section className="tracking-restaurant" key={sub.id}><div className="card-head"><div><p className="eyebrow">Restaurant</p><h2>{sub.restaurant.name}</h2></div><span className={`vendor-badge ${sub.status}`}>{labels[sub.status]}</span></div><ol className="tracking-timeline">{steps.map((step,index)=><li key={step} className={index<=current?'done':''}><span aria-hidden="true">{index<current?'✓':index+1}</span><b>{labels[step]}</b></li>)}</ol>{sub.items.map((item,index)=><div className="order-line" key={`${item.product_name}-${index}`}><span><b>{item.quantity} × {item.product_name}</b><small>{item.options?.map(option=>option.name).filter(Boolean).join(', ')||'Sans option'}</small></span><strong>{formatPrice(item.line_total)}</strong></div>)}{sub.events.length?<details><summary>Voir la chronologie détaillée</summary>{sub.events.map((event,index)=><p className="muted" key={`${event.created_at}-${index}`}>{new Intl.DateTimeFormat('fr-FR',{dateStyle:'short',timeStyle:'short'}).format(new Date(event.created_at))} · {labels[event.to_status]}</p>)}</details>:null}</section>})}
 <section className="tracking-address"><h2>{order.fulfillment==='delivery'?'Adresse de livraison':'Retrait au restaurant'}</h2>{order.fulfillment==='delivery'?<p>{order.address}<br/>{order.commune}</p>:<p>Présentez la référence {reference} lorsque la commande est prête.</p>}{order.customer_note?<p><strong>Instructions :</strong> {order.customer_note}</p>:null}</section></div>;
}
