'use client';
import {useEffect,useState} from 'react';import Link from 'next/link';import {formatPrice} from '@/lib/utils';
type Status={total:number;payment_status:string;statuses:string[]};type Payment={paymentUrl:string;merchantPhone:string};
export function OrderStatus({reference,token}:{reference:string;token?:string}){
 const[order,setOrder]=useState<Status|null>(null);const[missing,setMissing]=useState(false);const[payment,setPayment]=useState<Payment|null>(null);
 useEffect(()=>{const timer=setTimeout(()=>{const saved=sessionStorage.getItem(`come-eat-order-${reference}`);if(saved)try{setPayment(JSON.parse(saved))}catch{}},0);if(token)fetch(`/api/orders/${encodeURIComponent(reference)}?token=${encodeURIComponent(token)}`,{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(setOrder).catch(()=>setMissing(true));return()=>clearTimeout(timer)},[reference,token]);
 if(!token||missing)return <div className="container"><div className="card empty"><h2>Commande introuvable</h2><p>Utilisez le lien de suivi obtenu lors de la commande.</p><Link className="btn btn-dark" href="/menu">Retour au menu</Link></div></div>;
 return <div className="container" style={{paddingBottom:70}}><div className="card empty"><span>✓</span><p className="eyebrow">Commande créée</p><h1 className="page-title">Merci pour votre commande</h1><p className="lead">Référence <strong>{reference}</strong></p>{order?<><p style={{fontSize:22,fontWeight:900}}>{formatPrice(order.total)}</p><div className="notice">Paiement : <strong>{order.payment_status==='paid'?'Confirmé':'En attente'}</strong>.</div></>:<p>Chargement du suivi…</p>}{payment&&order?.payment_status!=='paid'?<div className="payment-next"><a className="btn btn-orange" href={payment.paymentUrl} target="_blank" rel="noopener noreferrer">Payer avec Wave</a><p>Compte marchand : <strong>{payment.merchantPhone}</strong><br/>Indiquez la référence <strong>{reference}</strong>.</p></div>:null}<Link href="/menu" className="btn btn-dark">Retour au menu</Link></div></div>;
}
