'use client';
import Image from 'next/image';
import Link from 'next/link';
import { useState } from 'react';
import type { Product,ProductOptionGroup,CartSelection } from '@/types';
import { formatPrice } from '@/lib/utils';
import { useCart } from './cart-provider';
import { useToast } from './toast-provider';
import { FavoriteButton } from './favorite-button';
import { ShareButton } from './share-button';

export function ProductDetail({product,groups}:{product:Product;groups:ProductOptionGroup[]}){
 const [selected,setSelected]=useState<CartSelection[]>([]); const [quantity,setQuantity]=useState(1); const [error,setError]=useState(''); const [adding,setAdding]=useState(false); const cart=useCart(); const toast=useToast();
 const toggle=(group:ProductOptionGroup,option:{id:string;name:string;price:number})=>setSelected(old=>{const exists=old.some(x=>x.optionId===option.id);if(exists){setError('');return old.filter(x=>x.optionId!==option.id)}const inGroup=old.filter(x=>x.groupId===group.id);if(group.maxChoices&&inGroup.length>=group.maxChoices){setError(`Vous pouvez choisir jusqu’à ${group.maxChoices} option${group.maxChoices>1?'s':''} dans ${group.name.toLocaleLowerCase('fr')}.`);return old}setError('');return [...old,{groupId:group.id,optionId:option.id,name:option.name,price:option.price}]});
 const total=(product.price+selected.reduce((sum,item)=>sum+item.price,0))*quantity; const orderable=product.available&&product.restaurantCanOrder!==false;
 const add=()=>{const missing=groups.find(group=>selected.filter(item=>item.groupId===group.id).length<Math.max(group.minChoices??0,group.required?1:0));if(missing){setError(`Choisissez ${missing.name.toLocaleLowerCase('fr')} avant de continuer.`);return}setAdding(true);cart.add(product,selected,quantity);toast('Produit ajouté au panier');window.setTimeout(()=>setAdding(false),450)};
 return <><div className="store-container product-breadcrumb"><Link href={product.restaurantSlug?`/restaurants/${product.restaurantSlug}`:'/menu'}>← Retour à la carte</Link><span>{product.restaurantName??'Menu'} / {product.name}</span></div><div className="store-container detail-grid"><div className="detail-gallery"><div className="detail-image">{product.image?<Image src={product.image.url} alt={product.image.alt} fill priority sizes="(max-width: 800px) 100vw, 50vw"/>:<span className="image-placeholder">COME & EAT</span>}<FavoriteButton productId={product.id}/></div></div><div className="detail-copy">{product.restaurantName?<Link className="product-restaurant" href={`/restaurants/${product.restaurantSlug}`}>{product.restaurantName}</Link>:null}<div className="product-title-row"><h1>{product.name}</h1><ShareButton title={`${product.name} — ${product.restaurantName||'Come & Eat'}`} text={`Découvrez ${product.name} chez ${product.restaurantName||'Come & Eat'} sur Come & Eat.`} path={`/menu/${product.slug}`} /></div><div className="detail-meta"><span className={orderable?'available':'unavailable'}>{!product.available?'● Indisponible':product.restaurantCanOrder===false?'● Restaurant fermé':'● Disponible'}</span>{product.categoryName?<span>{product.categoryName}</span>:null}</div><p className="lead">{product.description}</p><div className="detail-price"><small>Prix de base</small><strong>{formatPrice(product.price)}</strong></div>{groups.map(group=><fieldset className="option-box" key={group.id}><legend><span>{group.name}</span><small>{group.required?'Choix requis':'Facultatif'} · {group.maxChoices?`${group.maxChoices} choix maximum`:'Plusieurs choix possibles'}</small></legend>{group.options.filter(option=>option.available).map(option=><label className={`option-row ${selected.some(item=>item.optionId===option.id)?'selected':''}`} key={option.id}><span><input type="checkbox" name={group.id} checked={selected.some(item=>item.optionId===option.id)} onChange={()=>toggle(group,option)}/><i>{option.name}</i></span><strong>{option.price?`+ ${formatPrice(option.price)}`:'Inclus'}</strong></label>)}</fieldset>)}{error?<p className="detail-error" role="alert">{error}</p>:null}<div className="detail-order-bar"><div className="quantity-selector"><button type="button" onClick={()=>setQuantity(value=>Math.max(1,value-1))} aria-label="Réduire la quantité">−</button><b>{quantity}</b><button type="button" onClick={()=>setQuantity(value=>value+1)} aria-label="Augmenter la quantité">+</button></div><button className="btn btn-orange detail-add" disabled={!orderable||adding} aria-busy={adding} onClick={add}><span>{adding?'Ajout…':'Ajouter au panier'}</span><strong>{formatPrice(total)}</strong></button></div></div></div></>
}
