'use client';
import Image from 'next/image';
import Link from 'next/link';
import { useState } from 'react';
import type { Product,ProductOptionGroup,CartSelection } from '@/types';
import { formatPrice } from '@/lib/utils';
import { useCart } from './cart-provider';
import { useToast } from './toast-provider';

export function ProductDetail({product,groups}:{product:Product;groups:ProductOptionGroup[]}){
 const [selected,setSelected]=useState<CartSelection[]>([]); const [quantity,setQuantity]=useState(1); const cart=useCart(); const toast=useToast();
 const toggle=(group:ProductOptionGroup,option:{id:string;name:string;price:number})=>setSelected(old=>{const exists=old.some(x=>x.optionId===option.id);if(exists)return old.filter(x=>x.optionId!==option.id);const cleaned=group.multiple?old:old.filter(x=>x.groupId!==group.id);return [...cleaned,{groupId:group.id,optionId:option.id,name:option.name,price:option.price}]});
 const total=(product.price+selected.reduce((s,x)=>s+x.price,0))*quantity;
 return <><div className="store-container product-breadcrumb"><Link href="/menu">← Retour à la carte</Link><span>Menu / {product.name}</span></div><div className="store-container detail-grid"><div className="detail-gallery"><div className="detail-image">{product.image?<Image src={product.image.url} alt={product.image.alt} fill priority sizes="(max-width: 800px) 100vw, 50vw"/>:<span className="image-placeholder">COME & EAT</span>}<span className="rating large">★ 4.9 · 120 avis</span></div><div className="detail-thumbs"><button aria-label="Vue principale" className="active">🍽</button><button aria-label="Ingrédients">♧</button><button aria-label="Préparation">🔥</button></div></div><div className="detail-copy"><p className="section-kicker">🔥 Signature Come & Eat</p><h1>{product.name}</h1><div className="detail-meta"><span>◷ 15–20 min</span><span>♧ Préparé minute</span><span className={product.available?'available':'unavailable'}>{product.available?'● Disponible':'● Indisponible'}</span></div><p className="lead">{product.description}</p><div className="detail-price"><small>Prix de base</small><strong>{formatPrice(product.price)}</strong></div>{groups.map(g=><fieldset className="option-box" key={g.id}><legend><span>{g.name}</span><small>{g.required?'Choix requis':'Facultatif'} · {g.multiple?'Plusieurs choix':'Un choix'}</small></legend>{g.options.filter(o=>o.available).map(o=><label className={`option-row ${selected.some(x=>x.optionId===o.id)?'selected':''}`} key={o.id}><span><input type={g.multiple?'checkbox':'radio'} name={g.id} checked={selected.some(x=>x.optionId===o.id)} onChange={()=>toggle(g,o)}/><i>{o.name}</i></span><strong>{o.price?`+ ${formatPrice(o.price)}`:'Inclus'}</strong></label>)}</fieldset>)}<div className="detail-order-bar"><div className="quantity-selector"><button onClick={()=>setQuantity(q=>Math.max(1,q-1))} aria-label="Réduire la quantité">−</button><b>{quantity}</b><button onClick={()=>setQuantity(q=>q+1)} aria-label="Augmenter la quantité">+</button></div><button className="btn btn-orange detail-add" disabled={!product.available} onClick={()=>{cart.add(product,selected,quantity);toast('Produit ajouté au panier')}}><span>▣ Ajouter au panier</span><strong>{formatPrice(total)}</strong></button></div></div></div></>
}