'use server';
import {createClient} from '@/lib/supabase/server';
import {getPaymentProvider} from '@/lib/payments/provider';
import {sendOrderCreatedNotifications} from '@/lib/notifications/service';
export type CheckoutPayload={customerName:string;customerPhone:string;customerEmail?:string;fulfillment:'delivery'|'pickup';address?:string;commune?:string;note?:string;wantsCutlery:boolean;deliveryZoneId?:string;promotionCode?:string;idempotencyKey:string;items:Array<{productId:string;quantity:number;optionIds:string[]}>};
export type CheckoutQuote={subtotal:number;delivery_fee:number;discount_total:number;total:number;promotion_name?:string};
async function ensureRestaurantsCanOrder(db:Awaited<ReturnType<typeof createClient>>,items:CheckoutPayload['items']){const ids=[...new Set(items.map(item=>item.productId))];const{data:products,error:productError}=await db.from('products').select('restaurant_id').in('id',ids);if(productError)return productError.message;const restaurantIds=[...new Set((products??[]).map(row=>row.restaurant_id))];const{data,error}=await db.rpc('get_restaurant_ordering_statuses',{targets:restaurantIds});if(error)return error.message;const closed=(data??[]).find((row:{can_order:boolean;restaurant_name:string})=>!row.can_order);return closed?`${closed.restaurant_name} est actuellement fermé et ne peut pas accepter cette commande.`:null}
export async function quoteOrder(input:Pick<CheckoutPayload,'fulfillment'|'deliveryZoneId'|'promotionCode'|'items'>){const db=await createClient();const unavailable=await ensureRestaurantsCanOrder(db,input.items);if(unavailable)return{ok:false as const,error:unavailable};const{data,error}=await db.rpc('quote_marketplace_order',{payload:{fulfillment:input.fulfillment,delivery_zone_id:input.deliveryZoneId??null,promotion_code:input.promotionCode??'',items:input.items.map(item=>({product_id:item.productId,quantity:item.quantity,options:item.optionIds}))}});if(error)return{ok:false as const,error:error.message||'Le code ne peut pas être appliqué.'};return{ok:true as const,quote:data as CheckoutQuote}}
export async function placeOrder(input:CheckoutPayload){if(!input.items.length)return{ok:false as const,error:'Votre panier est vide.'};if(!/^[0-9a-f-]{36}$/i.test(input.idempotencyKey))return{ok:false as const,error:'Veuillez actualiser la page et réessayer.'};const db=await createClient();const unavailable=await ensureRestaurantsCanOrder(db,input.items);if(unavailable)return{ok:false as const,error:unavailable};const{data,error}=await db.rpc('place_marketplace_order',{payload:{customer_name:input.customerName,customer_phone:input.customerPhone,customer_email:input.customerEmail??'',fulfillment:input.fulfillment,address:input.address??'',commune:input.commune??'',customer_note:input.note??'',wants_cutlery:input.wantsCutlery,delivery_zone_id:input.deliveryZoneId??null,promotion_code:input.promotionCode??'',idempotency_key:input.idempotencyKey,payment_method:'wave',items:input.items.map(item=>({product_id:item.productId,quantity:item.quantity,options:item.optionIds}))}});if(error){console.error('checkout.place_order_failed',{code:error.code,message:error.message});return{ok:false as const,error:error.message||'La commande n’a pas pu être créée.'};}const order=data as {id:string;reference:string;total:number;tracking_token:string};const payment=await getPaymentProvider().createSession({orderReference:order.reference,amount:order.total,currency:'XOF'});await sendOrderCreatedNotifications(order.id);return{ok:true as const,order,payment}}
