import {createServerClient} from '@supabase/ssr';import {NextResponse,type NextRequest} from 'next/server';

const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabasePublishableKey=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
const supabaseAnonKey=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
const supabasePublicKey=supabasePublishableKey||supabaseAnonKey;

export async function proxy(request:NextRequest){try{if(!supabaseUrl||!supabasePublicKey){console.error('[admin-auth] proxy_configuration_missing');const code=supabaseUrl?'AUTH-KEY-MISSING':'AUTH-URL-MISSING';return NextResponse.redirect(new URL(`/admin/login?error=service&code=${code}`,request.url))}const url=supabaseUrl.replace(/\/rest\/v1\/?$/,'');let response=NextResponse.next({request});const db=createServerClient(url,supabasePublicKey,{cookies:{getAll:()=>request.cookies.getAll(),setAll(values){values.forEach(({name,value})=>request.cookies.set(name,value));response=NextResponse.next({request});values.forEach(({name,value,options})=>response.cookies.set(name,value,options))}}});const{data:{user},error:userError}=await db.auth.getUser();if(!user)return NextResponse.redirect(new URL('/admin/login',request.url));if(userError){console.error('[admin-auth] proxy_user_verification_failed',{code:userError.code});return NextResponse.redirect(new URL('/admin/login?error=service',request.url))}const{data:profile,error:profileError}=await db.from('profiles').select('role').eq('id',user.id).maybeSingle();if(profileError){console.error('[admin-auth] proxy_profile_read_failed',{code:profileError.code});return NextResponse.redirect(new URL('/admin/login?error=service',request.url))}if(!profile||!['admin','super_admin'].includes(profile.role))return NextResponse.redirect(new URL('/admin/login?error=acces',request.url));return response}catch(error){const value=error as{name?:string};console.error('[admin-auth] proxy_unexpected_failure',{name:value?.name});return NextResponse.redirect(new URL('/admin/login?error=service',request.url))}}
export const config={matcher:['/admin','/admin/((?!login(?:/|$)).*)']};
