-- Proposition de schéma Come & Eat — à appliquer uniquement lorsque le projet Supabase client existe.
create extension if not exists pgcrypto;
create type order_status as enum ('new','confirmed','preparing','ready','delivering','delivered','cancelled');
create type fulfillment_type as enum ('delivery','pickup');
create table media (id uuid primary key default gen_random_uuid(), name text not null, storage_path text not null unique, alt_text text not null default '', created_at timestamptz not null default now());
create table categories (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, media_id uuid references media(id) on delete set null, visible boolean not null default true, sort_order integer not null default 0, created_at timestamptz not null default now());
create table products (id uuid primary key default gen_random_uuid(), sku text not null unique, name text not null, slug text not null unique, category_id uuid not null references categories(id), price integer not null check(price>=0), description text not null default '', media_id uuid references media(id) on delete set null, available boolean not null default true, archived_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table option_groups (id uuid primary key default gen_random_uuid(), name text not null, required boolean not null default false, multiple boolean not null default false, sort_order integer not null default 0);
create table product_options (id uuid primary key default gen_random_uuid(), group_id uuid not null references option_groups(id) on delete cascade, name text not null, price integer not null default 0 check(price>=0), available boolean not null default true, sort_order integer not null default 0);
create table product_option_groups (product_id uuid references products(id) on delete cascade, group_id uuid references option_groups(id) on delete cascade, primary key(product_id,group_id));
create table delivery_zones (id uuid primary key default gen_random_uuid(), name text not null, fee integer not null default 0, active boolean not null default true);
create table customers (id uuid primary key default gen_random_uuid(), name text not null, phone text not null, email text, created_at timestamptz not null default now());
create table orders (id uuid primary key default gen_random_uuid(), reference text not null unique, customer_id uuid not null references customers(id), status order_status not null default 'new', fulfillment fulfillment_type not null, address text, zone_id uuid references delivery_zones(id), payment_method text not null, customer_note text, subtotal integer not null, delivery_fee integer not null default 0, total integer not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table order_items (id uuid primary key default gen_random_uuid(), order_id uuid not null references orders(id) on delete cascade, product_id uuid references products(id), product_name text not null, quantity integer not null check(quantity>0), unit_price integer not null, options jsonb not null default '[]');
create table promotions (id uuid primary key default gen_random_uuid(), name text not null, code text unique, discount_type text not null check(discount_type in ('percent','fixed')), value integer not null check(value>=0), active boolean not null default true, starts_at timestamptz, ends_at timestamptz);
create table site_settings (id boolean primary key default true check(id), restaurant_name text not null, phone text not null, email text, address text, currency text not null default 'XOF', delivery_enabled boolean not null default true, pickup_enabled boolean not null default true, content jsonb not null default '{}');
create index products_category_idx on products(category_id) where archived_at is null;
create index orders_status_created_idx on orders(status,created_at desc);
-- RLS et politiques devront être finalisées avec l’authentification avant la production.
