name: Deploy Come & Eat to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy-production:
    runs-on: ubuntu-latest

    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Install Vercel CLI
        run: npm install --global vercel@59.1.4

      - name: Validate project
        run: npm run lint && npm run typecheck && npm run test:ci && npm run build

      - name: Build and deploy on Vercel
        run: vercel deploy --yes --prod --token=${{ secrets.VERCEL_TOKEN }}
